### ISSUE TITLE
poise and chef-12.4.0

### ISSUE THREAD

**Issue by mdkent** [poise/poise#15]
We've been hitting a new issue since upgrading from chef-12.2.1 to chef-12.4.0:
```  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/wrap_hadoop/recipes/rundeck.rb
  ================================================================================

  NoMethodError
  -------------
  No resource or method named `rundeck_node_source_file' for `Chef::Resource::RundeckProject "data"'

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/wrap_hadoop/recipes/rundeck.rb:39:in `block in from_file'
    /var/chef/cache/cookbooks/wrap_hadoop/recipes/rundeck.rb:37:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/wrap_hadoop/recipes/rundeck.rb:

   32:
   33:  rundeck_acl 'apiadmin' do
   34:    source 'rundeck/apitoken.aclpolicy.erb'
   35:  end
   36:
   37:  rundeck_project 'data' do
   38:
   39>>   rundeck_node_source_file "data-#{node[:datacenter]}" do
   40:        query "datacenter:#{node[:datacenter]} AND recipes:wrap_hadoop\\:\\:common"
   41:    end
   42:
   43:  end
   44:
   45:  cookbook_file "/etc/rundeck/tokens.properties" do
   46:    source "rundeck/tokens.properties"
   47:    mode 0644
   48:  end
```
though it's unclear to me if this is a problem with poise or the integration in https://github.com/balanced-cookbooks/rundeck/blob/master/libraries/rundeck_node_source.rb.

This is using the latest poise master.

Any suggestions would be appreciated!

**Comment by coderanger** [comment]
12.4 changed how the DSL works and now in general resources and providers need to explicitly declare what DSL names they support. Adding `provides(:rundeck_node_source_file)` to the resource and provider classes should take care it.

**Comment by mdkent** [comment]
Ahh, thank you. I'll take it up with the rundeck maintainer.

**Comment by coderanger** [comment]
Given that that is also me, you don't have far to go ;-)
