### ISSUE TITLE
Resources in notifying_block having trouble finding resources in parent scope

### ISSUE THREAD

**Issue by Poohblah** [poise/poise#23]
See [the gist](https://gist.github.com/Poohblah/965f72b9cfcff3fdf921). We chatted a little bit about this on #chef yesterday, but we were unable to quickly reach a solution. The issue occurs with `include_recipe 'firewall'` both inside of and outside of the `notifying_block`.  The issue does not occur when placing the `firewall_rule` resource outside of the `notifying_block`.

**Comment by cbaenziger** [comment]
I too seem to be hitting issue when upgrading from Chef 11.18.12 to Chef 12.18.24 on Ubuntu 14.04:
````
Recipe: cobblerd::default
[...]
  * bash[cobbler-sync] action nothing (skipped due to action :nothing)
Recipe: cobblerd::web
[...]
Recipe: bcpc::cobbler
[...]
  * cobbler_image[ubuntu-12.04-mini] action import
    
================================================================================
    Error executing action `import` on resource 'cobbler_image[ubuntu-12.04-mini]'
    ================================================================================
    
    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    resource bash[ubuntu-12.04-mini-cobbler-import] is configured to notify resource bash[cobbler-sync] with action run, but bash[cobbler-sync] cannot be found in the resource collection. bash[ubuntu-12.04-mini-cobbler-import] is defined in /var/chef/cache/cookbooks/cobblerd/libraries/cobbler_image.rb:98:in `block (2 levels) in action_import'
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/cobblerd/libraries/cobbler_image.rb:51:in `block in action_import'
    /var/chef/cache/cookbooks/cobblerd/libraries/cobbler_image.rb:50:in `action_import'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb
    
    219: cobbler_image 'ubuntu-12.04-mini' do
    220:   source "#{get_binary_server_url}/ubuntu-12.04-hwe313-mini.iso"
    221:   os_version 'precise'
    222:   os_breed 'ubuntu'
    223:   action :import
    224: end
    225: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb:219:in `from_file'
    
    cobbler_image("ubuntu-12.04-mini") do
      action [:import]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :cobbler_image
      cookbook_name "bcpc"
      recipe_name "cobbler"
      source "http://10.0.100.3//ubuntu-12.04-hwe313-mini.iso"
      os_version "precise"
      os_breed "ubuntu"
      os_arch "x86_64"
      target "/var/chef/cache/ubuntu-12.04-mini.iso"
    end
    
    Platform:
    ---------
    x86_64-linux
    
Recipe: cobblerd::default
  * service[cobbler] action restart
    - restart service service[cobbler]
[...]
````

The code flow can be seen at: [cobbler_image.rb](https://github.com/cbaenziger/cobbler-cookbook/blob/1721f9fdc224bd6436448d88add5cbac908c609f/libraries/cobbler_image.rb#L109)
