### ISSUE TITLE
FrozenError - poise-monit

### ISSUE THREAD

**Issue by raphaunix** [poise/poise#35]
I have had a problem with the poise-monit a few days ago, can you help me? Thank you

```bash
139.10.0.123 Starting Chef Client, version 14.3.37
139.10.0.123 resolving cookbooks for run list: ["Webapps::spotlight", "backend_base::monit"]
139.10.0.123 Synchronizing Cookbooks:
139.10.0.123   - Webapps (1.8.0)
139.10.0.123   - backend_base (0.33.0)
139.10.0.123   - java (1.49.0)
139.10.0.123   - apt (6.1.4)
139.10.0.123   - windows (4.2.5)
139.10.0.123   - homebrew (5.0.4)
139.10.0.123   - locale (2.0.1)
139.10.0.123   - sysctl (0.8.1)
139.10.0.123   - ohai (5.2.2)
139.10.0.123   - system (0.11.2)
139.10.0.123   - cron (6.1.1)
139.10.0.123   - hostsfile (2.4.6)
139.10.0.123   - ntp (3.5.6)
139.10.0.123   - yum (5.1.0)
139.10.0.123   - build-essential (8.1.1)
139.10.0.123   - zabbix-agent (0.14.0)
139.10.0.123   - seven_zip (3.0.0)
139.10.0.123   - mingw (2.0.2)
139.10.0.123   - chocolatey (2.0.0)
139.10.0.123   - netdata (0.4.0)
139.10.0.123   - yum-epel (2.1.2)
139.10.0.123   - compat_resource (12.19.1)
139.10.0.123   - poise-monit (1.6.0)
139.10.0.123   - poise (2.8.1)
139.10.0.123   - poise-languages (2.1.2)
139.10.0.123   - poise-archive (1.5.0)
139.10.0.123   - poise-service (1.5.2)
139.10.0.123   - users (5.0.0)
139.10.0.123   - sudo (5.4.0)
139.10.0.123   - firewall (2.6.3)
139.10.0.123   - chef-sugar (4.0.0)
139.10.0.123   - chef_client_updater (1.0.2)
139.10.0.123   - chef_hostname (0.6.1)
139.10.0.123   - chef-client (8.1.8)
139.10.0.123   - logrotate (2.1.0)
139.10.0.123   - chef_nginx (6.1.1)
139.10.0.123   - zypper (0.4.0)
139.10.0.123   - poise-python (1.6.0)
139.10.0.123   - push-jobs (5.2.0)
139.10.0.123   - runit (4.1.1)
139.10.0.123   - packagecloud (1.0.0)
139.10.0.123   - chef-ingredient (2.3.0)
139.10.0.123   - ark (3.1.0)
139.10.0.123   - tomcat (2.5.2)
139.10.0.123   - maven (5.0.3)
139.10.0.123 Installing Cookbook Gems:
139.10.0.123 Compiling Cookbooks...
139.10.0.123 
139.10.0.123 ================================================================================
139.10.0.123 Recipe Compile Error in /var/chef/cache/cookbooks/poise-monit/libraries/default.rb
139.10.0.123 ================================================================================
139.10.0.123 
139.10.0.123 FrozenError
139.10.0.123 -----------
139.10.0.123 can't modify frozen Array
139.10.0.123 
139.10.0.123 Cookbook Trace:
139.10.0.123 ---------------
139.10.0.123   /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:220:in `included'
139.10.0.123   /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `include'
139.10.0.123   /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `poise_subresource_container'
139.10.0.123   /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:93:in `block in Poise'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:44:in `include'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:44:in `<class:Resource>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:43:in `<module:Monit>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:29:in `<module:Resources>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:26:in `<module:PoiseMonit>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:25:in `<top (required)>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources.rb:17:in `<top (required)>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/cheftie.rb:17:in `<top (required)>'
139.10.0.123   /var/chef/cache/cookbooks/poise-monit/libraries/default.rb:19:in `<top (required)>'
139.10.0.123 
139.10.0.123 Relevant File Content:
139.10.0.123 ----------------------
139.10.0.123 /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:
139.10.0.123 
139.10.0.123 213:                @container_default
139.10.0.123 214:              end
139.10.0.123 215:            end
139.10.0.123 216:  
139.10.0.123 217:            def included(klass)
139.10.0.123 218:              super
139.10.0.123 219:              klass.extend(ClassMethods)
139.10.0.123 220>>             klass.const_get(:HIDDEN_IVARS) << :@subcontexts
139.10.0.123 221:              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
139.10.0.123 222:            end
139.10.0.123 223:          end
139.10.0.123 224:  
139.10.0.123 225:          extend ClassMethods
139.10.0.123 226:        end
139.10.0.123 227:      end
139.10.0.123 228:    end
139.10.0.123 229:  end
139.10.0.123 
139.10.0.123 Additional information:
139.10.0.123 -----------------------
139.10.0.123       Ruby objects are often frozen to prevent further modifications
139.10.0.123       when they would negatively impact the process (e.g. values inside
139.10.0.123       Ruby's ENV class) or to prevent polluting other objects when default
139.10.0.123       values are passed by reference to many instances of an object (e.g.
139.10.0.123       the empty Array as a Chef resource default, passed by reference
139.10.0.123       to every instance of the resource).
139.10.0.123 
139.10.0.123       Chef uses Object#freeze to ensure the default values of properties
139.10.0.123       inside Chef resources are not modified, so that when a new instance
139.10.0.123       of a Chef resource is created, and Object#dup copies values by
139.10.0.123       reference, the new resource is not receiving a default value that
139.10.0.123       has been by a previous instance of that resource.
139.10.0.123 
139.10.0.123       Instead of modifying an object that contains a default value for all
139.10.0.123       instances of a Chef resource, create a new object and assign it to
139.10.0.123       the resource's parameter, e.g.:
139.10.0.123 
139.10.0.123       fruit_basket = resource(:fruit_basket, 'default')
139.10.0.123 
139.10.0.123       # BAD: modifies 'contents' object for all new fruit_basket instances
139.10.0.123       fruit_basket.contents << 'apple'
139.10.0.123 
139.10.0.123       # GOOD: allocates new array only owned by this fruit_basket instance
139.10.0.123       fruit_basket.contents %w(apple)
139.10.0.123 
139.10.0.123 
139.10.0.123 System Info:
139.10.0.123 ------------
139.10.0.123 chef_version=14.3.37
139.10.0.123 platform=ubuntu
139.10.0.123 platform_version=16.04
139.10.0.123 ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
139.10.0.123 program_name=/usr/bin/chef-client
139.10.0.123 executable=/opt/chef/bin/chef-client
139.10.0.123 
139.10.0.123 
139.10.0.123 Running handlers:
139.10.0.123 [2018-07-31T08:05:47-05:00] ERROR: Running exception handlers
139.10.0.123 Running handlers complete
139.10.0.123 [2018-07-31T08:05:47-05:00] ERROR: Exception handlers complete
139.10.0.123 Chef Client failed. 0 resources updated in 07 seconds
139.10.0.123 [2018-07-31T08:05:47-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
139.10.0.123 [2018-07-31T08:05:47-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
139.10.0.123 [2018-07-31T08:05:47-05:00] FATAL: FrozenError: can't modify frozen Array
```

**Comment by coderanger** [comment]
As mentioned in the other ticket, a fixed release is already out.
